### PR TITLE
Improved support for the default config file

### PR DESCRIPTION
**Pull request by bgood**
One thing I need this to do is use a default config file.  So, I added a const for the default location, and a check to see if there is a default, and use it if the file exists.

The default file allows me to now issue the start, stop, etc commands without need it specify any arguments!

Ben

### CODE REVIEW

**Comment by simonoff** [comment]
I don't think this is a good idea.
The main profit of golden_brindle is a starting of multiple Rails/Rack applications at once.
Without any arguments golden_brindle starting Rails/Rack app with 4 worker processes and binding it on 8080 port.
If you want to get a default config for your app then run 'golden_brindle configure' and get it in config/brindle.yml.

**Comment by bgood** [comment]
My problem is that my application is large enough that it runs on multiple machines all config'ed the same.  So what I want to be able to do is run golden_brindle (start|restart|stop) from anywhere on a machine and have it start, stop or restart my app based on the config file.

The way golden brindle currently works is that I need to do that from the app root or specify the fully qualified path to the config file.  All of which is a pain, especially if I'm fighting a production fire at 2 am.  This was one of the really nice things about the way mongrel_cluster_ctl worked.

Thoughts?

Ben

PS. I symlink /etc/golden_brindle/brindle.yml to the actual file in config/, which came from 'golden_brindle configure'

**Comment by simonoff** [comment]
Why not use [init](https://github.com/simonoff/golden_brindle/blob/master/resources/golden_brindle) script?
And run /etc/init.d/golden_brindle start/stop from any where on your system?
Put only one config file to /etc/brindles directory or symlink it.

**Comment by bgood** [comment]
That will work.

Thanks

**Pull request closed without merging**
